### ISSUE TITLE
Not all images are downloading

### ISSUE THREAD

**Issue by Movva** [sdushantha/insta-dl#6]
If there is array of images in single link only the front image is downloading and rest are ignored.

**Comment by sdushantha** [comment]
This is the type of post you mean right? https://www.instagram.com/p/BbKHUF_jcDo/

I tried finding where these images are but i cant. Can you try having a look?

😄

**Comment by jonbarrow** [comment]
```
I tried finding where these images are but i cant.
```
I took a look. It seems like the other images don't even exist as far as the page is concerned, when the page is first loaded that is. Checking the pages sources, it loads the other images dynamically when you click the chevron. But even when loading in the other images, it doesn't add them to the page it just replaces the current image with the new requested one. So there is never actually a time when more than one is on the same page at the same time.

I'm sure there's some fuckery you could do to get the other images, like using a headless client (similar to puppeteer) and actually "clicking" the chevron to load each image then ripping it, but it would be exponentially slower.

**Comment by pilo21** [comment]
[91mInvalid username![0m

i got this error for al name i insert

**Comment by sdushantha** [comment]
@pilo21 insta-dl has stopped working because Instragram did something with their JSON data. Normally, when you visited https://www.instagram.com/USERNAME/?_a=1 you would get some JSON data, but now there is nothing. So i don't know how to get the data.
