### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by odysseusmax** [sdushantha/insta-dl#7]
Can you please point out where i can find the 'json' format reference

**Comment by sdushantha** [comment]
This is the url to the JSON data for a user. Replace USERNAME with the username you want.
```
https://www.instagram.com/USERNAME/?__a=1
```

I am a little unsure about what you mean about "'json' format reference". If you are talking about the documentation or something similar on using python with JSON data then you might want to check out this link: https://realpython.com/python-json/

If I did not answer your question, please do let me know and I will try give a better answer :)

**Comment by odysseusmax** [comment]
Thanks for your reply, and sorry I was unclear. What I wanted was is there any docs for the method, not json docs.

**Comment by sdushantha** [comment]
Hmm...I dont think so there are docs for the method. The way I found that you could get the JSON data by adding `?__a=1` to the end of the url is by finding it online. I think I just stumbled upon it someday and then thought of making a script which actually uses that data.
