### ISSUE TITLE
Can you please help on downloading slider/album images into separate folders?

### ISSUE THREAD

**Issue by hustlerwolf** [sdushantha/insta-dl#8]
Hey @sdushantha,

First of all thanks for this python scripts for downloading images from Instagram, it helps a lot. Due to the recent increase usage of album type posts, I was wondering if we can download all posts to separate folder so if any post will have more than one image that all will go to the same folder, so we can easily keep track of all posts separately.

Thanks in advance

**Comment by sdushantha** [comment]
@hustlerwolf Im really so sorry to say this, but I will not be working on this project anymore because the Instagram API has changed and I dont have time to rewrite the code to fit the new API :(
